version: "3"
services:
  subconverter:
    image: siriling/subconverter:latest
    container_name: subconverter
    restart: unless-stopped
    # network_mode: bridge
    ports:
      - ${SUBWEB_PORT}:80
      - 25500:25500
    environment:
      -e API_URL='http://127.0.0.1:25500'
      -e SITE_NAME='订阅转换'
    volumes:
      - /root/appdata/subconverter/conf:/usr/share/nginx/html/conf

  myurls:
    image: siriling/myurls:latest
    container_name: myurls
    restart: unless-stopped
    # network_mode: bridge
    ports:
      - "8002:8002"
    environment:
      - MYURLS_DOMAIN=${url.siriling.com:81}
      - MYURLS_TTL=${MYURLS_TTL}
      - MYURLS_REDIS=${MYURLS_REDIS}
    volumes:
      - /root/appdata/myurls/logs:/app/logs
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: myurls-redis
    restart: unless-stopped
    # network_mode: bridge
    volumes:
      - /root/appdata/redis/data:/data